# Generated by Django 5.2.6 on 2025-10-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattendance_app', '0002_employerprofile_studentprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployerProfile',
            new_name='TeacherProfile',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], default='student', max_length=10, verbose_name='User Type'),
        ),
    ]
