# Generated by Django 5.2.6 on 2025-11-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_studentprofile_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='student_id_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
