# Generated by Django 5.2.6 on 2025-11-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_alter_studentprofile_student_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='employee_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
