"""
Django settings for cattendance_project project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# ===============================================
# BASE DIRECTORY
# ===============================================
BASE_DIR = Path(__file__).resolve().parent.parent


# ===============================================
# SECURITY SETTINGS
# ===============================================
SECRET_KEY = 'django-insecure-q9ks0-+yi5n-81f8+!hqx%_lvdz35bbf&j1#0!ylszp4zthq@l'
DEBUG = True
ALLOWED_HOSTS = []


# ===============================================
# INSTALLED APPS
# ===============================================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Project Apps
    'auth_app',
    'core_app',
    'dashboard_app',
    'admin_app',
]

AUTH_USER_MODEL = 'auth_app.User'


# ===============================================
# MIDDLEWARE
# ===============================================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ===============================================
# URLS / WSGI
# ===============================================
ROOT_URLCONF = 'cattendance_project.urls'
WSGI_APPLICATION = 'cattendance_project.wsgi.application'


# ===============================================
# SESSION SETTINGS
# ===============================================
SESSION_COOKIE_NAME = "cattendance_session"
ADMIN_SESSION_COOKIE_NAME = "cattendance_admin_session"


# ===============================================
# TEMPLATES
# ===============================================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# ===============================================
# DATABASE CONFIGURATION
# ===============================================
DATABASES = {
    "default": dj_database_url.config(
        default="sqlite:///db.sqlite3",
        conn_max_age=600,
        ssl_require=False
    )
}


# ===============================================
# PASSWORD VALIDATION
# ===============================================
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ===============================================
# INTERNATIONALIZATION
# ===============================================
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Manila'  # changed from UTC
USE_I18N = True
USE_TZ = True


# ===============================================
# STATIC FILES
# ===============================================
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"


# ===============================================
# DEFAULT PRIMARY KEY
# ===============================================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ===============================================
# SUPABASE CONFIGURATION
# ===============================================
# You can either load from .env or directly define here

SUPABASE_URL = os.getenv("SUPABASE_URL", "https://jbsfkipzulstrwvugrec.supabase.co")
SUPABASE_KEY = os.getenv("SUPABASE_KEY", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impic2ZraXB6dWxzdHJ3dnVncmVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk1NTY1NjEsImV4cCI6MjA3NTEzMjU2MX0.Cu-QSqBnJFlQ61LWldtxRFElt2OKHGxbL_prDRoGA1A")

# If you want to store in .env instead (recommended for production):
# .env file example:
# SUPABASE_URL=https://jbsfkipzulstrwvugrec.supabase.co
# SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...

