"""
Django settings for cattendance_project project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# ===============================================
# BASE DIRECTORY
# ===============================================
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '.onrender.com', 'csit327-g1-cattendance.onrender.com']
CSRF_TRUSTED_ORIGINS = ['https://*.onrender.com', 'https://csit327-g1-cattendance.onrender.com']


# ===============================================
# INSTALLED APPS
# ===============================================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Project Apps
    'auth_app',
    'core_app',
    'dashboard_app',
    'admin_app',
]

AUTH_USER_MODEL = 'auth_app.User'


# ===============================================
# MIDDLEWARE
# ===============================================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# ===============================================
# URLS / WSGI
# ===============================================
ROOT_URLCONF = 'cattendance_project.urls'
WSGI_APPLICATION = 'cattendance_project.wsgi.application'


# ===============================================
# SESSION SETTINGS
# ===============================================
SESSION_COOKIE_NAME = "cattendance_session"
ADMIN_SESSION_COOKIE_NAME = "cattendance_admin_session"


# ===============================================
# TEMPLATES
# ===============================================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# ===============================================
# DATABASE CONFIGURATION
# ===============================================
DATABASES = {
    "default": dj_database_url.config(
        default="sqlite:///db.sqlite3",
        conn_max_age=600,  # persistent connections
        ssl_require=False  # Try without SSL requirement first
    )
}


# ===============================================
# PASSWORD VALIDATION
# ===============================================
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ===============================================
# INTERNATIONALIZATION
# ===============================================
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Manila'  # changed from UTC
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'  
# STATICFILES_DIRS = [BASE_DIR / 'static']  # Not needed - Django finds app static folders automatically
STATIC_ROOT = BASE_DIR / 'staticfiles' 



# ===============================================
# DEFAULT PRIMARY KEY
# ===============================================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


SUPABASE_URL = os.getenv('SUPABASE_URL')
SUPABASE_ANON_KEY = os.getenv('SUPABASE_ANON_KEY') 
SUPABASE_SERVICE_KEY = os.getenv('SUPABASE_SERVICE_KEY')

# Logging configuration for better debugging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}