# Generated by Django 5.2.6 on 2025-10-21 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0002_user_must_change_password_alter_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('schedule_days', models.CharField(max_length=50)),
                ('schedule_time', models.CharField(max_length=50)),
                ('student_count', models.PositiveIntegerField(default=0)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='auth_app.teacherprofile')),
            ],
        ),
    ]
