# Generated by Django 5.2.6 on 2025-10-25 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0004_remove_class_end_time_remove_class_meeting_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], default='ongoing', max_length=20)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='dashboard_app.class')),
                ('schedule_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.classschedule')),
            ],
        ),
    ]
