# Generated by Django 5.2.6 on 2025-10-26 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_user_must_change_password_alter_user_user_type'),
        ('dashboard_app', '0005_classsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='dashboard_app.classsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.studentprofile')),
            ],
        ),
    ]
