# Generated by Django 5.2.6 on 2025-10-26 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_user_must_change_password_alter_user_user_type'),
        ('dashboard_app', '0006_sessionattendance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sessionattendance',
            unique_together={('session', 'student')},
        ),
    ]
