# Generated by Django 5.2.6 on 2025-10-30 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0007_alter_sessionattendance_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionattendance',
            name='marked_via_qr',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SessionQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='dashboard_app.classsession')),
            ],
        ),
        # migrations.DeleteModel(
        #     name='AttendanceRecord',
        # ),
    ]
