# Generated by Django 5.2.6 on 2025-10-31 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0008_sessionattendance_marked_via_qr_sessionqrcode_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttendanceRecord',
        ),
    ]
