# Generated by Django 5.2.6 on 2025-11-17 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0009_delete_attendancerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='allowed_ip_ranges',
            field=models.JSONField(blank=True, help_text="List of allowed IP CIDR ranges, e.g., ['192.168.1.0/24']", null=True),
        ),
        migrations.AddField(
            model_name='sessionattendance',
            name='client_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionattendance',
            name='ip_validated',
            field=models.BooleanField(default=False),
        ),
    ]
