# Generated by Django 5.2.6 on 2025-11-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0009_delete_attendancerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionattendance',
            name='is_present',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
