# Generated by Django 5.2.6 on 2025-11-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_user_must_change_password_alter_user_user_type'),
        ('dashboard_app', '0010_alter_sessionattendance_is_present'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('teacher', 'code', 'academic_year', 'semester')},
        ),
    ]
