# Generated by Django 5.2.6 on 2025-11-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0011_alter_class_code_alter_class_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionqrcode',
            name='qr_active',
            field=models.BooleanField(default=False),
        ),
    ]
