# Generated by Django 5.2.6 on 2025-11-29 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0012_sessionqrcode_qr_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionattendance',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
