# Generated by Django 5.2.6 on 2025-11-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0013_sessionattendance_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='teacher_ip',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
